name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Clean install
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install dependencies
        run: |
          npm install --no-package-lock --legacy-peer-deps
          npm install --no-package-lock --legacy-peer-deps -D tailwindcss@latest postcss@latest autoprefixer@latest
          npm install --no-package-lock --legacy-peer-deps -D @types/node@latest @types/react@latest @types/react-dom@latest typescript@latest
          npm install --no-package-lock --legacy-peer-deps -D eslint@latest eslint-config-next@latest @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest

      - name: Create Tailwind config if missing
        run: |
          if [ ! -f tailwind.config.js ]; then
            npx tailwindcss init -p
          fi

      - name: Verify installations
        run: |
          echo "Checking dependency versions:"
          npm list react react-dom next tailwindcss framer-motion
          echo "Checking node_modules structure:"
          ls -la node_modules/tailwindcss
          ls -la node_modules/framer-motion
          ls -la node_modules/@heroicons

      - name: Build with Next.js
        run: |
          npm run build
          touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 