name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Clean install
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - name: Install core dependencies
        run: |
          npm install next@latest react@latest react-dom@latest

      - name: Install dev dependencies
        run: |
          npm install -D typescript @types/node @types/react @types/react-dom
          npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
          npm install -D @heroicons/react framer-motion next-themes

      - name: Verify Tailwind installation
        run: |
          echo "Checking Tailwind installation:"
          npm list tailwindcss
          ls -la node_modules/tailwindcss

      - name: Create Tailwind config if missing
        run: |
          if [ ! -f tailwind.config.ts ]; then
            npx tailwindcss init -p
          fi

      - name: Build with Next.js
        run: |
          npm run build
          touch out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 