name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          echo "Installing core dependencies..."
          npm install --no-package-lock --legacy-peer-deps next@14.1.0 react@18.2.0 react-dom@18.2.0
          echo "Installing Tailwind and PostCSS..."
          npm install --no-package-lock --legacy-peer-deps -D tailwindcss@3.4.1 postcss@8.4.33 autoprefixer@10.4.17 postcss-import@16.0.0
          echo "Installing remaining dependencies..."
          npm install --no-package-lock --legacy-peer-deps

      - name: Verify installation
        run: |
          echo "Checking installed packages..."
          npm list tailwindcss postcss autoprefixer
          echo "Checking node_modules..."
          ls -la node_modules/tailwindcss || echo "Tailwind not found"
          ls -la node_modules/postcss || echo "PostCSS not found"

      - name: Build with Next.js
        run: |
          echo "Starting Next.js build..."
          NODE_ENV=production npm run build
          touch out/.nojekyll
          echo "Build completed."

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 